Django/11_Authorization/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('posts/',include('posts.urls')),
    path('register/',include('register.urls')),
    path('users/',include('users.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django/11_Authorization/myproject/posts/urls.py
from django.urls import path
from . import views

app_name= 'posts'

urlpatterns = [
    path('',views.posts_list,name="list"),
    path('new-post/',views.post_new,name="new-post"),
    path('<slug:slug>/',views.post_page,name="page"),
]

Django/11_Authorization/myproject/register/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.register_home),
]

Django/11_Authorization/myproject/users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('register/',views.register_view,name="register"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
    
]

Django/11_Authorization/myproject/posts/models.py
from django.db import models


# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True);
    banner = models.ImageField(default='Img1.png',blank=True)
    
    def __str__(self):
        return self.title
    

Django/11_Authorization/myproject/register/models.py
from django.db import models

# Create your models here.

Django/11_Authorization/myproject/users/models.py
from django.db import models

# Create your models here.

Django/11_Authorization/myproject/myproject/views.py
#from django.http import HttpResponse 
from django.shortcuts import render

def homepage(request):
    #return HttpResponse("Hello World! I'm Home")
    return render(request, 'home.html')

def about(request):
    #return HttpResponse("My About Page")
    return render(request,'about.html')

Django/11_Authorization/myproject/posts/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
def posts_list(request):
    all_posts= Post.objects.all().order_by('-date') #newest first
    return render(request,'posts/posts_list.html',{'posts':all_posts});

def post_page(request,slug):
    my_post= get_object_or_404(Post,slug=slug  )
    return render(request,'posts/post_page.html',{'post':my_post});

@login_required(login_url='/users/login/')# this check if user is logged in if not redirect them to /users/login page
def post_new(request):
    return render(request,'posts/post_new.html')
    

Django/11_Authorization/myproject/register/views.py
from django.shortcuts import render
from django.http import HttpResponse 
# Create your views here.

def register_home(request):
    return render(request,'register_home.html')

Django/11_Authorization/myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def register_view(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            login(request,form.save())
            return redirect("posts:list")
    else:
        form=UserCreationForm()
    return render(request,'users/register.html',{"form":form})

def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request,form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:list')
    else:#GET
        form=AuthenticationForm()
    return render(request,'users/login.html',{"form":form})

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('posts:list')

Django/11_Authorization/myproject/posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title%}
     New Post Page
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        
    </section>
{% endblock %}

Django/11_Authorization/myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title%}
      {{post.title}}
{% endblock %}

{% block content %}
    <section>
        <img src="{{post.banner.url}}" alt="{{post.title}}"/>
    <h1>{{post.title}}</h1>
    <p>{{post.date}}</p>
    <p>{{post.body}}</p>
    </section>
{% endblock %}

Django/11_Authorization/myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title%}
    Posts
{% endblock %}

{% block content %}
    <section>
    <h1>Posts</h1>
        {% for post in posts %}
        <article class='post'>
            <h3>
                <a href="{% url 'posts:page' slug=post.slug %}">
                {{post.title}}
                </a>
            </h3>
            <p>{{post.date}}</p>
            <p>{{post.body}}</p>
        </article>
        {% endfor %}
    </section>
{% endblock %}

Django/11_Authorization/myproject/templates/about.html
{% extends 'layout.html' %}

{% block title%}
    About
{% endblock %}

{% block content %}
    <h1>ABOUT</h1>
    <p>Check out my <a href="/">home</a> Page. </p>
{% endblock %}

Django/11_Authorization/myproject/templates/home.html
{% extends 'layout.html' %}

{% block title%}
    Home
{% endblock %}

{% block content %}
     <h1>Home</h1>
    <p>Check out my <a href="/about">about</a> Page. </p>
{% endblock %}

Django/11_Authorization/myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Django App {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}?v=7" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/" class="{% if request.path == '/' %}active{% endif %}"
        ><span role="img" aria-label="Home">Home🏡</span></a
      >| <a href="/about"><span role="img" aria-label="About">About😀</span></a
      >|
      <a href="{% url 'posts:list' %}"
        ><span role="img" aria-label="Posts">Posts📰</span></a
      >|
      {% if user.is_authenticated %}
      <a href="{% url 'posts:new-post' %}"
        ><span role="img" aria-label="New Post" title="New Post">➕</span></a
      >|
      
      
      <form
        class="logout"
        action="{% url 'users:logout' %}"
        method="post"
      >
      {% csrf_token %}  
      <button class='logout-button' aria-label="user logout" title='user logout'>Logout👋</button>
      </form>
      
      {% else %}
       <a href="{% url 'users:register' %}"
        ><span role="img" aria-label="registration">®️</span></a
      >|
      <a href="{% url 'users:login' %}"
        ><span role="img" aria-label="Login">Login🔐</span></a
      >|
      {% endif %}
      
    </nav>
    <main>{%block content %} {%endblock%}</main>
  </body>
</html>

Django/11_Authorization/myproject/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title%}
      User Login
{% endblock %}

{% block content %}
   <h1>User Login</h1>
   <form class="form-width-validation" action="/users/login/" method="post">
      {% csrf_token %}
      {{form}}
      {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}"/>
      {%endif%}
      <button class="form-submit">Submit</button> {% comment %} single button is bydefault type='submit' {% endcomment %}
   </form>
{% endblock %}

Django/11_Authorization/myproject/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title%}
      Register a User
{% endblock %}

{% block content %}
   <h1>Register a New User</h1>
   <form class="form-width-validation" action="/users/register/" method="post">
      {% csrf_token %}
      {{form}}
      <button class="form-submit">Submit</button> {% comment %} single button is bydefault type='submit' {% endcomment %}
   </form>
{% endblock %}